name: PR CI and  develop push CI

# 1. 이벤트 설정
on:
  # PR 요청이 들어올 때 빌드와 테스트 실행
  pull_request:
    branches:
      - main  # main 브랜치로의 PR일 때 실행
      - develop
    types: # opened, synchronize, reopened를 추가하여 PR이 열리거나 업데이트될 때 작업이 실행
      - opened
      - synchronize
      - reopened

  # develop 브랜치에 push가 되면 실행
  push:
    branches:
      - develop

# 2. 빌드 및 테스트 잡
jobs:
  CI-start:
    runs-on: ubuntu-latest
    env:
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_TITLE: ${{ secrets.EMAIL_TITLE }}
      EMAIL_CONTENT_TEMPLATE: ${{ secrets.EMAIL_CONTENT_TEMPLATE }}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      AWS_S3_ACCESSKEY: ${{ secrets.AWS_S3_ACCESSKEY }}
      AWS_S3_SECRETKEY: ${{ secrets.AWS_S3_SECRETKEY }}
      AWS_S3_BUKET_NAME: ${{ secrets.AWS_S3_BUKET_NAME }}
      AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
      VC_URL: ${{ secrets.VC_URL }}
      VC_APIKEY: ${{ secrets.VC_APIKEY }}
      AWS_SQS_ACCESS_KEY_ID: ${{ secrets.AWS_SQS_ACCESS_KEY_ID }}
      AWS_SQS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SQS_SECRET_ACCESS_KEY }}
      AWS_SQS_QUEUE_URL: ${{ secrets.AWS_SQS_QUEUE_URL }}
      AWS_SQS_VIRTUAL_QUEUE_NAME: ${{ secrets.AWS_SQS_VIRTUAL_QUEUE_NAME }}
    permissions:
      pull-requests: write  # PR에 댓글, 체크 실행을 할 수 있는 권한
      checks: write          # 체크 결과를 기록할 권한
      actions: read          # GitHub Actions의 정보를 읽을 수 있는 권한


    steps:
      # Node.js 설치
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      # 코드 체크아웃
      - name: Check out code
        uses: actions/checkout@v4

      # JDK 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle Wrapper 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # gradlew 파일 실행권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
        # Gradle 의존성 캐시 설정
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Json 파일 업로드
      - name: Create JSON Config File
        env:
          TTS_JSON_CONTENT: ${{ secrets.TTS_JSON_CONTENT }}
        run: |
          echo "${TTS_JSON_CONTENT}" | base64 -d  > src/main/resources/tts.json
          echo $TTS_JSON_CONTENT

      - name: Set Cache Directory Permissions
        run: |
          if [ -d "~/.sonar/cache" ]; then chmod -R 777 ~/.sonar/cache; fi
          if [ -d "~/.gradle/caches" ]; then chmod -R 777 ~/.gradle/caches; fi

      # build and Test
      - name: Build and Test
        run: ./gradlew build

      # 소나큐브 실행
      - name: Sonarqube Scan
        run: ./gradlew sonar -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      # 3-1. 소나큐브 패키지 캐싱 설정
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

        # Gradle Test를 실행한다
      - name: Test with Gradle
        run: ./gradlew --info test

        # Test 후 Report 생성
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: '**/build/test-results/test/TEST-*.xml'

      - name: Lint Checks
        run: ./gradlew check